### ISSUE TITLE
Add ability to allow certain sections on each page type

### ISSUE THREAD

**Issue by mylesthedev** [coreiho/silverstripe-sections#2]
Add ability to allow certain sections only on each page type.
E.g. Home page might only require 3 section types and no others.

This would be best done via the config file where you would list the excluded section types for each page type.

Page would be the highest level e.g. excluded section types here should filter down on to sub classes e.g. HomePage.

**Comment by gorriecoe** [comment]
Fixed.  You can now read about this in the documention in https://github.com/coreiho/silverstripe-sections#section-configurtation
